#!/usr/bin/env python

import signal, os, time, gobject, gtk, string, pango
from threading import Timer

# another line bytes the dust

import keyhand, pedconfig
from edmenu import *

SCROLLGAP = 2           # Gap between the page boundary and scroll
PAGEUP = 20             # One page worth of scroll

# Do not redifne this here, as it is determined by the gtk lib
TABSTOP = 8             # One tabstop worth of spaces

# profile line
#got_clock = time.clock()   
# profiled code here
#print  "Str", time.clock() - got_clock        

chore = None

keywords =  "def", "import", "from", "for", "while", "len", "return", \
            "range", "if", "not", "abs", "any", "all", "min", "max",  \
            "map", "print"

class pedDoc(gtk.DrawingArea):

    #notebook = None

    def __init__(self, buff, parent, appwin):
        
        # Save params
        self.appwin = appwin; self.parwin = parent

        # Gather globals
        self.keyh = pedconfig.pedconfig.keyh
        #self.pedwin = pedconfig.pedconfig.pedwin

        # Init vars
        self.xpos = 0; self.ypos = 0
        self.changed = False; self.colsel = False

        self.xsel = -1; self.ysel = -1
        self.xsel2 = -1; self.ysel2 = -1
        self.caret = []; self.caret.append(0); self.caret.append(0)        
        self.maxlinelen = 0
        self.focus = False

        # Init configurables
        self.scgap = SCROLLGAP      
        self.pgup  = PAGEUP
        self.tabstop = TABSTOP
        # Process buffer into list
        self.text = str.split(buff, "\n")
        for aa in self.text:       
            xlen = len(aa)  
            if self.maxlinelen < xlen:
                self.maxlinelen = xlen

        # Parent widget                 
        gtk.DrawingArea.__init__(self)
        self.set_flags(gtk.CAN_FOCUS | gtk.SENSITIVE)
        self.pangolayout = self.create_pango_layout("a")
    
        # Set default background color
        '''colormap = gtk.widget_get_default_colormap()
        color = colormap.alloc_color("#d0d0d0")
        self.modify_bg(gtk.STATE_NORMAL, color)'''
        
        # Our font
        fd = pango.FontDescription()
        fd.set_size(14*1024); fd.set_family("mono")
        self.pangolayout.set_font_description(fd)

        # Get Pango steps
        self.cxx, self.cyy = self.pangolayout.get_pixel_size()
        ts = self.pangolayout.get_tabs()
        if ts == None: self.tabstop = TABSTOP    
        else: al, self.tabstop = ts.get_tab(0)

        #print "tabstop", self.tabstop
        # Set up scroll bars        
        self.hadj = gtk.Adjustment(0,0, 100, 1, 15, 25);
        self.vadj = gtk.Adjustment(0,0, 100, 1, 15, 25);
        
        self.vscroll = gtk.VScrollbar(self.vadj)
        self.hscroll = gtk.HScrollbar(self.hadj)
        
        # We connect scrollers after construction
        self.hadj.connect("value-changed", self.hscroll_cb)
        self.vadj.connect("value-changed", self.vscroll_cb)
        
        #self.www = gtk.gdk.screen_width();
        #self.hhh = gtk.gdk.screen_height();
        
        # Start up with initial size 
        #self.set_size_request(3*self.www/4,    self.hhh/5)

        self.set_events(    gtk.gdk.POINTER_MOTION_MASK |
                            gtk.gdk.POINTER_MOTION_HINT_MASK |
                            gtk.gdk.BUTTON_PRESS_MASK |
                            gtk.gdk.BUTTON_RELEASE_MASK |
                            gtk.gdk.KEY_PRESS_MASK |
                            gtk.gdk.KEY_RELEASE_MASK )
    
        self.set_events(    gtk.gdk.ALL_EVENTS_MASK )
      

        self.connect("expose-event", self.area_expose_cb)
        self.connect("motion-notify-event", self.area_motion)
        self.connect("button-press-event", self.area_button)
        self.connect("button-release-event", self.area_button)
        self.connect("key-press-event", self.area_key)
        self.connect("key-release-event", self.area_key)
        self.connect("focus", self.area_focus)
        self.connect("configure_event", self.configure_event)
        self.connect("size-request", self.size_request)
        self.connect("size-allocate", self.size_alloc)    
        self.connect("scroll-event", self.scroll_event)    
        #self.connect("enter-notify-event", self.area_enter)
        #self.connect("leave-notify-event", self.area_leave)
        self.connect("focus-in-event", self.focus_in_cb)    
        self.connect("focus-out-event", self.focus_out_cb)    
        
    def destroy(self, win, act):
        print "event", win, act        

    def focus_out_cb(self, widget, event):
        self.focus = False
        self.currented = None
        #print "focus_out_cb", widget, event
    
    def focus_in_cb(self, widget, event):
        self.focus = True
        self.currented = self
        print "focus_in_cb"
    
    def grab_focus_cb(self, widget):
        print "grab_focus_cb", widget
        pass
        
    def area_enter(self, widget, event):
        print "area_enter"
        
    def area_leave(self, widget, event):
        print "area_leave"

    def scroll_event(self, widget, event):
        if event.direction == gtk.gdk.SCROLL_UP:
            self.ypos -= self.pgup / 2
        else:
            self.ypos += self.pgup / 2

        # Contain, show
        self.ypos = max(0, self.ypos)
        self.ypos = min(len(self.text), self.ypos)        
        self.invalidate()
        
    def hscroll_cb(self, widget):
        #print "hscroll", widget.get_value()
        self.xpos = int(widget.get_value())
        self.invalidate()

    def vscroll_cb(self, widget):
        #print "vscroll", widget.get_value()
        self.ypos = int(widget.get_value())
        self.invalidate()

    def size_request(self, widget, req):
        #print "size_request", req
        pass

    def size_alloc(self, widget, req):
        #print "size_alloc", req
        pass

    def configure_event(self, widget, event):
        #print "configure_event", event
        #self.grab_focus()
        #self.width = 0; self.height = 0
        #self.invalidate()
        #print self, event
        pass
        
    def _draw_text(self, gc, x, y, text, foreground = None, background = None):
        #print "draw_text"
        self.pangolayout.set_text(text)
        xx, yy = self.pangolayout.get_pixel_size()
        self.window.draw_layout(gc, x, y, self.pangolayout, foreground, background)
        return xx, yy

	# Calculate tabs up to till count
    def calc_tabs(self, strx, till):
        idx = 0; cnt = 0
        xlen = min(len(strx), till); 
        while True:
            if idx >= xlen: break
            chh = strx[idx]
            if  chh == "\t":
                cnt += self.tabstop - (cnt % self.tabstop)
            else:
                cnt += 1
            idx += 1
        return cnt

    def area_expose_cb(self, area, event):

        #print "area_expose_cb()", event.area.width, event.area.height
        
        hhh = self.get_height()
        xlen = len(self.text)

        style = self.get_style()
        self.gc = style.fg_gc[gtk.STATE_NORMAL]

        #got_clock = time.clock()   
            
        # Paint text        
        xx = 0; yy = 0; 
        cnt = self.ypos;
        while cnt <  xlen:
            dx, dy = self._draw_text(self.gc, xx, yy, self.text[cnt])
            cnt = cnt + 1
            yy += dy
            if yy > hhh:
                break

        #print  "texy", time.clock() - got_clock        
        # Paint selection
        colormap = gtk.widget_get_default_colormap()
        bgcolor = colormap.alloc_color("#4488ff")
        color = colormap.alloc_color("#000000")
        gcx = gtk.gdk.GC(self.window); gcx.copy(self.gc)
        
        xx = 0; yy = 0; 
        cnt = self.ypos;
    
        # Normalize 
        xssel = min(self.xsel, self.xsel2)
        xesel = max(self.xsel, self.xsel2)
        yssel = min(self.ysel, self.ysel2)
        yesel = max(self.ysel, self.ysel2)
 
        if xssel != -1:
            while cnt <  xlen:
                if cnt >= yssel and cnt <= yesel:
                    line = self.text[cnt]
                    frag = line[xssel:xesel]
                    self._draw_text(gcx, xssel * self.cxx, yy, frag,
                     color, bgcolor)
                cnt = cnt + 1
                yy += self.cyy
                if yy > hhh:
                    break

        #print  "sel", time.clock() - got_clock        
        # Color keywords
        color   = colormap.alloc_color("#44aaff")
        clcolor = colormap.alloc_color("#88ff44")
        cocolor = colormap.alloc_color("#0000ff")
        stcolor = colormap.alloc_color("#ff44ff")

        # Very primitive coloring, compromize for speed
        xx = 0; yy = 0; 
        cnt = self.ypos;
        while cnt <  xlen:
            line = self.text[cnt]

            for kw in keywords:
                ff = line.find(kw)
                if ff >= 0:
                    ff2 = self.calc_tabs(line, ff)                    
                    self._draw_text(gcx, ff2 * self.cxx, yy, line[ff:ff+len(kw)],
                        color, None)

            cc = line.find("class")
            if cc >= 0:
                    cc2 = self.calc_tabs(line, cc)                    
                    self._draw_text(gcx, cc2 * self.cxx, yy, line[cc:cc+5],
                    clcolor, None)
        
            ccc = line.find("#"); cccc = line.find('"')

            # See if hash preceeds quote (if any)
            if ccc >= 0 and (cccc > ccc or cccc == -1):
                ccc2 = self.calc_tabs(line, ccc)                    
                self._draw_text(gcx, ccc2 * self.cxx, yy, line[ccc:],
                        cocolor, None)
            else:
                qqq = line.find('"'); 
                if qqq >= 0:
                    qqq += 1
                    qqqq = line.find('"', qqq)
                    if qqqq >= 0:
                            qqq2 = self.calc_tabs(line, qqq)                    
                            self._draw_text(gcx, qqq2 * self.cxx, yy, line[qqq:qqqq],
                            stcolor, None)

            cnt = cnt + 1
            yy += self.cyy
            if yy > hhh:
                break

        #print  "kw", time.clock() - got_clock        
        
        self._drawcaret()        
        return True

    # --------------------------------------------------------------------
    # Draw caret

    def _drawcaret(self):

        #print "drawing caret", self.caret[0], self.caret[1], \
        #        self.caret[0] * self.cxx, self.caret[1] * self. cyy  
                
        if self.focus == False:
            return

        colormap = gtk.widget_get_default_colormap()
        color = colormap.alloc_color("#008888")
        
        gcx = gtk.gdk.GC(self.window); gcx.copy(self.gc)
        gcx.set_foreground(color)
      
        xx = self.caret[0] * self.cxx #+ self.cxx / 2
        yy = self.caret[1] * self.cyy
        cw = self.cxx / 2

        # Top, left right, buttom
        self.window.draw_line(gcx, xx, yy, xx + cw, yy)
        self.window.draw_line(gcx, xx + 1, yy, xx + 1, yy + self.cyy )
        self.window.draw_line(gcx, xx + 3, yy, xx + 3, yy + self.cyy )
        self.window.draw_line(gcx, xx , yy + self.cyy, xx + cw, yy + self.cyy )

    def area_motion(self, area, event):
        #print "motion event", event
        pass

    # --------------------------------------------------------------------
    def set_caret(self, xx, yy):

        # Needs scroll?
        xxx, yyy = self.get_size()        
        need_inval = False        
        xlen = len(self.text)

         # Put it back in view:                    
        hhh = yyy - self.scgap * self.cyy
        if  yy * self.cyy  > hhh:
            #print "Scroll from caret down"
            self.ypos += yy - (yyy / self.cyy - self.scgap) 
            yy = yyy / self.cyy - self.scgap 
            need_inval = True
       
        colormap = gtk.widget_get_default_colormap()
        color = colormap.alloc_color("#008888")
        
        gcx = gtk.gdk.GC(self.window); gcx.copy(self.gc)
        gcx.set_foreground(color)
           
        if yy < self.scgap and self.ypos > 0:
            #print "Scroll from caret up"
            #self.ypos = yy - yyy / self.cyy
            self.ypos += yy - self.scgap            
            yy = self.scgap
            need_inval = True
            
        if self.ypos >  xlen - self.scgap:
               self.ypos = xlen - self.scgap            

        if self.ypos < 0:
            self.ypos = 0
            
        oldx = self.caret[0] * self.cxx; 
        oldy = self.caret[1] * self.cyy

        self.caret[0] = xx; self.caret[1] = yy

        # Low limit
        if self.caret[0] < 0: self.caret[0] = 0
        if self.caret[1] < 0: self.caret[1] = 0

        # High Limit
        xxxx = xxx / self.cxx; yyyy = yyy / self.cyy
        if self.caret[0] > xxxx: self.caret[0] = xxxx       
        if self.caret[1] > yyyy: self.caret[1] = yyyy       
               
        wxx = self.caret[0] * self.cxx
        wyy = self.caret[1] * self.cyy

        # Optimize cursor movement invalidation
        rect = gtk.gdk.Rectangle(wxx, wyy, self.cxx * self.cxx /2, self.cyy + 1)
        self.invalidate(rect)

        rect = gtk.gdk.Rectangle(oldx, oldy, self.cxx + self.cxx /2 , self.cyy + 1)
        self.invalidate(rect)

        self.mained.update_statusbar2(self.caret[0] + self.xpos, self.caret[1] + self.ypos)
               
        if  need_inval:
            self.invalidate()            
        
    def clearsel(self):
        old = self.xsel
        self.xsel = -1;   self.ysel = -1
        self.xsel2 = -1;  self.ysel2 = -1
        if old != -1:
            self.invalidate()

    def area_button(self, area, event):
        if  event.type == gtk.gdk.BUTTON_PRESS and event.button == 3:
            ttt = "Press right mouse"
            #print "Right Click at x=", event.x, "y=", event.y
            self.poprclick(area, event)                       
        elif  event.type == gtk.gdk.BUTTON_PRESS and event.button == 1:
            ttt = "Press left mouse"
            print "Left Click at x=", event.x, "y=", event.y
            # Find current line    
            self.set_caret(int(event.x) / self.cxx, 
                                 int(event.y) / self.cyy )                                
        else:
            ttt = "Release"

        #print "button event ", "type = ", ttt, "x= ", event.x, \
        #    "y= ", event.y, "button = ", event.button                
        self.grab_focus()
        return True

    # Call key handler
    def area_key(self, area, event):
        self.keyh.handle_key(self, area, event)
        return True

     # Invalidate current line
    def inval_line(self):
        rect = gtk.gdk.Rectangle(0, self.caret[1] * self.cyy, 
                self.get_width(), self.cyy)
        self.invalidate(rect)
   
    def invalidate(self, rect = None):                        
        if rect == None:
            ww, hh = self.window.get_size()
            rect = gtk.gdk.Rectangle(0,0, ww, hh)
        #print "Invalidate:", rect
        self.window.invalidate_rect(rect, False)

    def area_focus(self, area, event):
        #print "peddoc area focus", event
        return False

    def poprclick(self, widget, event):
        #print "Making rclick"
        mm = self.build_menu(self.window, rclick_menu)
        mm.popup(None, None, None, event.button, event.time)

        # Create a new menu-item with a name...
        #menu = gtk.Menu()
        #menu.append(self.create_menuitem("Menu 1", self.menuitem_response1))
        #menu.append(self.create_menuitem("Menu 2", self.menuitem_response2))
        #menu.append(self.create_menuitem("Menu 3", self.menuitem_response3))
        #menu.popup(None, None, None, event.button, event.time)

    def menuitem_response1(self, widget, string):
        self.draw_segments(10, 200)
        print "response1 %s" % string

    def menuitem_response2(self, widget, string):
        print "response2 %s" % string

    def menuitem_response3(self, widget, string):
        print "response3 %s" % string

    def activate_action(self, action):
        dialog = gtk.MessageDialog(self, gtk.DIALOG_DESTROY_WITH_PARENT,
            gtk.MESSAGE_INFO, gtk.BUTTONS_CLOSE,
            'You activated action: "%s" of type "%s"' % (action.get_name(), type(action)))
        # Close dialog on user response
        dialog.connect ("response", lambda d, r: d.destroy())
        dialog.show()

    def create_menuitem(self, string, action):
        rclick_menu = gtk.MenuItem(string)
        rclick_menu.connect("activate", action, string);
        rclick_menu.show()        
        return rclick_menu
   
        # Create the menubar and toolbar
        action_group = gtk.ActionGroup("DocWindowActions")
        action_group.add_actions(entries)      
        return action_group

    def build_menu(self, window, items):
        accel_group = gtk.AccelGroup()
        item_factory = gtk.ItemFactory(gtk.Menu, "<pydoc>", accel_group)
        item_factory.create_items(items)
        self.item_factory = item_factory
        return item_factory.get_widget("<pydoc>")

    def get_size(self):
        rect = self.get_allocation()
        return rect.width, rect.height

    def get_height(self):
        rect = self.get_allocation()
        return rect.height

    def get_width(self):
        rect = self.get_allocation()
        return rect.width

    def do_chores():
        Timer(1, run_async_time).start()

def run_async_time():

    global chore
    print "From async_time", time.time()
    '''if chore:
        chore();
        chore = None               # Run once'''




